### ISSUE TITLE
Pulse secure VPN changed the key

### ISSUE THREAD

**Issue by johnlemon87** [majgis/psproxy#1]
New key of the Network setup for Pulse Secure changed with last version.
"net.juniper.pulse.nc.main" has become "net.pulsesecure.pulse.nc.main"

**Comment by ghost** [comment]
Thanks, just saw this.

**Comment by ghost** [comment]
This update is in v2.0.0.  Thank you @shaine for the PR, sorry I didn't see it and merge it sooner.
